#ifndef STUDENT_CODE_H
#define STUDENT_CODE_H
const char* student_python_code = 
"# =========================================================================\n"
"# UCT Micromouse - Live Multi-Sensor & ToF Signal Diagnostics\n"
"# =========================================================================\n"
"# Demonstrates:\n"
"#   1. uct_mouse.get_tof()         -> Default reliable filtered distances (mm)\n"
"#   2. uct_mouse.get_tof_raw()     -> Unfiltered raw distances (mm)\n"
"#   3. uct_mouse.get_tof_signals() -> Return signal strength in kcps\n"
"#   4. uct_mouse.display_text()    -> Live multi-line OLED telemetry\n"
"# =========================================================================\n"
"\n"
"import uct_mouse\n"
"import time\n"
"\n"
"def main():\n"
"    if not uct_mouse.init():\n"
"        print(\"Error: uct_mouse.init() failed.\")\n"
"        return\n"
"\n"
"    print(\"==================================================\")\n"
"    print(\"  UCT Micromouse: Live ToF & Signal Diagnostics   \")\n"
"    print(\"==================================================\")\n"
"    print(\"Format: [Sensor] Filtered(mm) | Raw(mm) | Signal(kcps)\")\n"
"\n"
"    count = 0\n"
"    while True:\n"
"        # 1. Read all three ToF telemetry streams\n"
"        tof_filt = uct_mouse.get_tof()\n"
"        tof_raw  = uct_mouse.get_tof_raw()\n"
"        tof_sig  = uct_mouse.get_tof_signals()\n"
"        \n"
"        # 2. Extract Center, Left, Right\n"
"        l_f, fl_f, c_f, fr_f, r_f = tof_filt\n"
"        l_r, fl_r, c_r, fr_r, r_r = tof_raw\n"
"        l_s, fl_s, c_s, fr_s, r_s = tof_sig\n"
"        \n"
"        # 3. Print periodically to Serial REPL\n"
"        if count % 5 == 0:\n"
"            print(f\"C: {c_f:4d} mm (raw:{c_r:4d}, sig:{c_s:4d} kcps) | \"\n"
"                  f\"L: {l_f:4d} (sig:{l_s:3d}) | R: {r_f:4d} (sig:{r_s:3d})\")\n"
"\n"
"        # 4. Update OLED Display\n"
"        # Row 0 is kept as default ('MicroPython')\n"
"        # Rows 1-3 display live readings\n"
"        uct_mouse.display_text(1, f\"C: {c_f}mm ({c_s}k)\")\n"
"        uct_mouse.display_text(2, f\"L:{l_f} R:{r_f}\")\n"
"        uct_mouse.display_text(3, f\"Raw C:{c_r}mm\")\n"
"        \n"
"        uct_mouse.delay_ms(100)\n"
"        count += 1\n"
"\n"
"if __name__ == \"__main__\":\n"
"    main()\n"
;
#endif
