/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "# =========================================================================\n"
            "# UCT Micromouse - Live Multi-Sensor & ToF Signal Diagnostics\n"
            "# =========================================================================\n"
            "# Demonstrates:\n"
            "#   1. uct_mouse.get_tof()         -> Default reliable filtered distances (mm)\n"
            "#   2. uct_mouse.get_tof_raw()     -> Unfiltered raw distances (mm)\n"
            "#   3. uct_mouse.get_tof_signals() -> Return signal strength in kcps\n"
            "#   4. uct_mouse.display_text()    -> Live multi-line OLED telemetry\n"
            "# =========================================================================\n"
            "import uct_mouse\n"
            "import time\n"
            "def main():\n"
            "    if not uct_mouse.init():\n"
            "        print(\"Error: uct_mouse.init() failed.\")\n"
            "        return\n"
            "    print(\"==================================================\")\n"
            "    print(\"  UCT Micromouse: Live ToF & Signal Diagnostics   \")\n"
            "    print(\"==================================================\")\n"
            "    print(\"Format: [Sensor] Filtered(mm) | Raw(mm) | Signal(kcps)\")\n"
            "    count = 0\n"
            "    while True:\n"
            "        # 1. Read all three ToF telemetry streams\n"
            "        tof_filt = uct_mouse.get_tof()\n"
            "        tof_raw  = uct_mouse.get_tof_raw()\n"
            "        tof_sig  = uct_mouse.get_tof_signals()\n"
            "        \n"
            "        # 2. Extract Center, Left, Right\n"
            "        l_f, fl_f, c_f, fr_f, r_f = tof_filt\n"
            "        l_r, fl_r, c_r, fr_r, r_r = tof_raw\n"
            "        l_s, fl_s, c_s, fr_s, r_s = tof_sig\n"
            "        \n"
            "        # 3. Print periodically to Serial REPL\n"
            "        if count % 5 == 0:\n"
            "            print(f\"C: {c_f:4d} mm (raw:{c_r:4d}, sig:{c_s:4d} kcps) | \"\n"
            "                  f\"L: {l_f:4d} (sig:{l_s:3d}) | R: {r_f:4d} (sig:{r_s:3d})\")\n"
            "        # 4. Update OLED Display\n"
            "        # Row 0 is kept as default ('MicroPython')\n"
            "        # Rows 1-3 display live readings\n"
            "        uct_mouse.display_text(1, f\"C: {c_f}mm ({c_s}k)\")\n"
            "        uct_mouse.display_text(2, f\"L:{l_f} R:{r_f}\")\n"
            "        uct_mouse.display_text(3, f\"Raw C:{c_r}mm\")\n"
            "        \n"
            "        uct_mouse.delay_ms(100)\n"
            "        count += 1\n"
            "if __name__ == \"__main__\":\n"
            "    main()\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

