/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __uct_mouse__H
#define __uct_mouse__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_uct_mouse(Args *args);

void uct_mouse_clear_display(PikaObj *self);
void uct_mouse_delay_ms(PikaObj *self, int ms);
void uct_mouse_display_text(PikaObj *self, int row, char* text);
void uct_mouse_dump_logs(PikaObj *self);
void uct_mouse_erase_flash(PikaObj *self);
int uct_mouse_get_button(PikaObj *self);
PikaObj* uct_mouse_get_encoders(PikaObj *self);
pika_float uct_mouse_get_gyro(PikaObj *self);
PikaObj* uct_mouse_get_line_sensors(PikaObj *self);
int uct_mouse_get_ticks_ms(PikaObj *self);
PikaObj* uct_mouse_get_tof(PikaObj *self);
pika_float uct_mouse_get_vbatt(PikaObj *self);
int uct_mouse_init(PikaObj *self);
void uct_mouse_log_custom(PikaObj *self, char* json_str);
void uct_mouse_set_encoder_polarity(PikaObj *self, int left_polarity, int right_polarity);
void uct_mouse_set_led(PikaObj *self, int led_idx, int state);
void uct_mouse_set_motors(PikaObj *self, int left_pwm, int right_pwm);
void uct_mouse_set_polarity(PikaObj *self, int left_polarity, int right_polarity);

#endif
